<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Razarth.Modules</AssemblyName>
    <RootNamespace>Razarth.Modules</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Razarth.Core.Shared\Razarth.Core.Shared.csproj" />
  </ItemGroup>

</Project>
